# Generated by Django 4.2 on 2023-04-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftrans_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passphrase',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
